
import { ObjectId } from 'mongodb';

export interface CompetitorAnalysis {
  name: string;
  website?: string;
  fundingTotal?: number;
  lastFundingRound?: {
    amount: number;
    date: Date;
    investors: string[];
    stage: string;
  };
  founded?: number;
  employees?: string;
  valuation?: number;
  revenueEstimate?: string;
  businessModel?: string;
  keyFeatures?: string[];
  strengths?: string[];
  weaknesses?: string[];
  targetCustomers?: string[];
  marketShare?: number;
  growthRate?: number;
}

export interface MarketTrend {
  trend: string;
  description: string;
  industry: string[];
  impactLevel: 'Low' | 'Medium' | 'High';
  timeframe: 'Short-term' | 'Mid-term' | 'Long-term';
  sources: string[];
  relatedStartups?: string[];
  opportunities?: string[];
  threats?: string[];
  sentimentScore?: number; // NLP sentiment analysis score
  momentumScore?: number; // Trend momentum/acceleration
  dateIdentified: Date;
}

export interface TrendingStartup {
  name: string;
  website?: string;
  description?: string;
  industry: string[];
  fundingStage?: string;
  totalFunding?: number;
  lastFundingDate?: Date;
  lastFundingAmount?: number;
  investors?: string[];
  tractionMetrics?: {
    users?: number;
    revenue?: string;
    growth?: string;
    other?: Record<string, any>;
  };
  foundedYear?: number;
  location?: string;
  founders?: string[];
  source: 'Crunchbase' | 'AngelList' | 'ProductHunt' | 'TechCrunch' | 'Other';
  scrapedDate: Date;
  trendingScore: number; // Calculated score based on various metrics
}

export interface MarketInsight {
  _id?: ObjectId;
  industry: string[];
  marketSize: number;
  cagr: number;
  year: number;
  trends: MarketTrend[];
  competitors: CompetitorAnalysis[];
  trendingStartups?: TrendingStartup[];
  keyPlayers: string[];
  regulatoryConsiderations?: string[];
  barriers?: string[];
  technologicalDrivers?: string[];
  consumerBehaviors?: string[];
  report?: string;
  lastUpdated: Date;
  dataSource?: string[]; // Where this data was sourced from
  aiGeneratedInsights?: string[]; // Insights generated by AI
  sentimentAnalysis?: {
    overall: number; // -1 to 1 score
    keyTerms: Record<string, number>;
  };
}
